version: "3"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qa-page
    entrypoint: sh entrypoint.sh
    working_dir: /home/node
    ports:
      - 3000:3000
    volumes:
      - .:/home/node
